baseURL = "https://league-curriculum.github.io/Motors/"
title = "Motors Clinic"
theme = "curriculum-hugo-theme"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
    title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[params]
  curriculum_version = "0.20260314.2"
  instructorGuide = true
  github_repo = "https://github.com/league-curriculum/Motors"

