baseURL = "https://curriculum.jointheleague.org/motors/"
title = "Motors Clinic"
theme = "curriculum-hugo-theme"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
    title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[params]
  instructorGuide = true
