name: Publish Docs

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change directory to docs
      run: cd docs

    - name: Run make publish
      run: make publish